version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: acat_postgres
    environment:
      - POSTGRES_DB=acat_system_dev
      - POSTGRES_USER=acat_user
      - POSTGRES_PASSWORD=dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: acat_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  web:
    build: .
    container_name: acat_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=acat_system.settings.development
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
