# Generated by Django 5.0 on 2025-07-08 00:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Denuncia",
                "verbose_name_plural": "Tipos de Denuncia",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InfractionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("LEVE", "Leve"),
                            ("MODERADA", "Moderada"),
                            ("GRAVE", "Grave"),
                            ("MUY_GRAVE", "Muy Grave"),
                        ],
                        default="MODERADA",
                        max_length=20,
                        verbose_name="Nivel de Severidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Infracción",
                "verbose_name_plural": "Tipos de Infracción",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EnvironmentalComplaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "sitada_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Número en SITADA"
                    ),
                ),
                (
                    "police_report_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Número de informe policial",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Coordenadas geográficas del incidente",
                        srid=4326,
                        verbose_name="Ubicación",
                    ),
                ),
                (
                    "infraction_date",
                    models.DateField(verbose_name="Fecha de la infracción"),
                ),
                (
                    "accused_name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del imputado"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del incidente",
                        verbose_name="Descripción detallada",
                    ),
                ),
                (
                    "evidence_photos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="URLs de las fotos de evidencia",
                        verbose_name="Fotos de evidencia",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En Proceso"),
                            ("RESUELTO", "Resuelto"),
                            ("ARCHIVADO", "Archivado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "complaint_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="complaints.complainttype",
                        verbose_name="Tipo de denuncia",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_complaints",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "protected_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="core.protectedarea",
                        verbose_name="Área Silvestre Protegida",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="core.sector",
                        verbose_name="Sector",
                    ),
                ),
                (
                    "infraction_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="complaints.infractiontype",
                        verbose_name="Nombre de infracción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Denuncia Ambiental",
                "verbose_name_plural": "Denuncias Ambientales",
                "ordering": ["-infraction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sitada_number"], name="complaints__sitada__518fa4_idx"
                    ),
                    models.Index(
                        fields=["infraction_date"],
                        name="complaints__infract_124684_idx",
                    ),
                    models.Index(
                        fields=["status"], name="complaints__status_82d47d_idx"
                    ),
                    models.Index(
                        fields=["protected_area", "sector"],
                        name="complaints__protect_f44a15_idx",
                    ),
                ],
            },
        ),
    ]
