# Generated by Django 5.0 on 2025-07-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentalcomplaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("in_progress", "En Proceso"),
                    ("resolved", "Resuelto"),
                    ("dismissed", "Desestimado"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
